Repository SE2-group-gamma/monopoly, pull requests merged in 2023-04, with the labels that each got.

#21 fix(HostGame): changed Layout to be compatible with smaller devices
  app/src/main/res/layout/host_game.xml
Labels: UI

#25 Add Network Service Discovery Registration
  app/src/main/java/com/example/monopoly/ui/HostGame.java
  app/src/main/java/com/example/monopoly/ui/NSDServer.java
Labels: Networking

#31 Game board
  app/build.gradle
  app/src/main/java/com/example/monopoly/gamelogic/Board.java
  app/src/main/java/com/example/monopoly/gamelogic/Field.java
  app/src/main/java/com/example/monopoly/gamelogic/Player.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_first.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/test/java/com/example/monopoly/BoardTest.java
  app/src/test/java/com/example/monopoly/FieldTest.java
  app/src/test/java/com/example/monopoly/PlayerTest.java
Labels: Game Logic
